name: exoplanet-detector
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - lightkurve
      - astroquery
      - tensorflow
      - torch
      - transformers
      - wandb